"""add an email column

Revision ID: 14733c37a386
Revises: 4d4b2b0697fe
Create Date: 2019-02-10 22:00:51.198264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14733c37a386'
down_revision = '4d4b2b0697fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
