"""add a author column

Revision ID: 1fe77c664506
Revises: 16069c9ac8ae
Create Date: 2019-02-14 08:27:00.417869

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fe77c664506'
down_revision = '16069c9ac8ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('myauthor', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'myauthor')
    # ### end Alembic commands ###
