"""drop author column

Revision ID: 928c8e9dfdaf
Revises: 1fe77c664506
Create Date: 2019-02-14 10:47:24.891914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '928c8e9dfdaf'
down_revision = '1fe77c664506'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pitches', 'myauthor')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pitches', sa.Column('myauthor', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
